services:
  - type: web
    name: attendance-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt &&
      mkdir -p /opt/render/project/src/.chrome-for-testing &&
      cd /opt/render/project/src/.chrome-for-testing &&
      wget -q --timeout=30 --tries=3 https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chrome-linux64.zip &&
      wget -q --timeout=30 --tries=3 https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip &&
      unzip -q chrome-linux64.zip &&
      unzip -q chromedriver-linux64.zip &&
      chmod +x chrome-linux64/chrome chromedriver-linux64/chromedriver &&
      rm *.zip &&
      ls -la /opt/render/project/src/.chrome-for-testing/ &&
      /opt/render/project/src/.chrome-for-testing/chrome-linux64/chrome --version &&
      /opt/render/project/src/.chrome-for-testing/chromedriver-linux64/chromedriver --version
    startCommand: python -m gunicorn app:app --bind=0.0.0.0:$PORT --workers=2 --threads=2 --timeout=300 --preload --log-level=info --max-requests=1000 --max-requests-jitter=100
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: CHROME_BIN
        value: /opt/render/project/src/.chrome-for-testing/chrome-linux64/chrome
      - key: CHROMEDRIVER_PATH
        value: /opt/render/project/src/.chrome-for-testing/chromedriver-linux64/chromedriver
      - key: PYTHONUNBUFFERED
        value: "1"